spring.application.name=driver-vehicle-service

spring.data.mongodb.uri=mongodb+srv://yashodarawishmi_db_user:Wishmi2026@cluster0.ttpznt3.mongodb.net/DriverVehicleDB?retryWrites=true&w=majority&authSource=admin&appName=Cluster0


spring.data.mongodb.database=DriverVehicleDB
