spring.application.name=fare-payment-service

spring.data.mongodb.uri=mongodb://localhost:27017/fare_payment_db

server.port=8083

ridelink.jwt.secret=${RIDELINK_JWT_SECRET:RideLinkDemoSecretKeyForJwtSigningMustBeLongEnough123}