spring.application.name=ride-service

spring.data.mongodb.uri=mongodb://localhost:27017/ride_db

server.port=8082

ridelink.jwt.secret=${RIDELINK_JWT_SECRET}

ridelink.driver-service.url=http://localhost:8080